# Two services: backend API on 5000, frontend (nginx) on 80
services:
  backend:
    build: ./server
    container_name: backend2server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
    container_name: frontend2server
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
